# Description: This file is used to run services for application without go code
# to run use the command: docker-compose -f docker-compose-local.yml up

version: "3.8"

services:
  redis:
    image: redis:7.0.7-alpine
    container_name: user_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - user_network

  postgres:
    image: postgres:14.6-alpine
    container_name: user_postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
      POSTGRES_PORT: 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - user_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus_container
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - user_network

  node_exporter:
    container_name: node_exporter_container
    image: prom/node-exporter
    ports:
      - '9101:9100'
    networks:
      - user_network

  grafana:
    container_name: grafana_container
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - user_network

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - user_network

networks:
  user_network:
    driver: bridge